# Generated by Django 4.2.2 on 2023-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_dice_seller_alter_purchase_buyer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='image',
            field=models.ImageField(height_field=255, null=True, upload_to=None, width_field=255),
        ),
    ]
