# Generated by Django 4.2.2 on 2023-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_dice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='image',
            field=models.ImageField(height_field=255, null=True, upload_to='dice_images/', width_field=255),
        ),
    ]
