# Generated by Django 4.2.2 on 2023-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_dice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
