# Generated by Django 4.2.2 on 2023-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_dice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='code',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
