# Generated by Django 4.2.2 on 2023-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_dice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
